; PlatformIO Project Configuration File
;======================================
[platformio]
;default_envs = menu_app
default_envs = radio_app
;efault_envs = btls_app

[env]
board = esp-wrover-kit
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip ;Arduino 3.3.9
framework = arduino
upload_protocol = esptool
upload_speed = 230400
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.bootloader = dio
board_build.filesystem = littlefs
board_build.partitions = PartitionTables/RadioESP32_8mb.csv
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, time
monitor_echo = yes
lib_ldf_mode = chain
lib_compat_mode = off
lib_deps = 
    ArduinoJson
    Wire
    densaugeo/base64@^1.4.0
    olikraus/U8g2@^2.35.7
extra_scripts = 
    scripts/custom_targets.py
build_flags = 
    -D VERSION=2.0.0                           ;no vX.X.X !!!
    -D BOARD_HAS_PSRAM
;    -mfix-esp32-psram-cache-issue             ;(not needed for rev.3 chips)
    -mfix-esp32-psram-cache-strategy=memw
    -D USER_SETUP_LOADED
    -D ST7735_DRIVER
    -D ST7735_BLACKTAB
    -D TFT_MISO=-1
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=21
    -D TFT_DC=22
    -D TFT_RST=-1
    -D TOUCH_CS=-1
    -D CORE_DEBUG_LEVEL=2
    -D CONFIG_ARDUHAL_LOG_COLORS=1
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1
    -D AUTOSHUTDOWN ; comment if HW is not equipped with a circuit for turning on and off with one button
    -D BATTERY      ; comment if HW is not equipped with a circuit for measuring battery voltage
;    -D DEBUG


[env:menu_app]
build_src_filter = -<*> -<btls/> +<menu/>
lib_deps = 
    ${env.lib_deps}
    ESP32Async/ESPAsyncWebServer@^3.11.2
extra_scripts =
    ${env.extra_scripts}
    post:scripts/app_deploy.py
;Here the standard built-in Upload cannot be used to write the application,
;because PlatformIO cannot choose the correct partition to upload!
;You need to use the utility PROJECT TASKS/menu_app/Custom/Upload custom binary
build_flags = 
    ${env.build_flags}
    -D ROLE_MENU
    -D CONFIG_ASYNC_TCP_USE_WDT=1
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
    -D CONFIG_ASYNC_TCP_PRIORITY=10
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=15360
    -D DATAWEB=false

[env:radio_app]
build_src_filter = +<*> -<btls/> -<menu/>
lib_deps = 
    ${env.lib_deps}
    ESP32Async/ESPAsyncWebServer@^3.11.2
    https://github.com/schreibfaul1/ESP32-audioI2S/archive/refs/tags/4.0.0.zip
    https://github.com/Arduino-IRremote/Arduino-IRremote/archive/refs/tags/v4.7.1.zip
extra_scripts = 
    ${env.extra_scripts}
    post:scripts/app_deploy.py
; Only here can the standard built-in Upload be used to write the partition table and application !
build_flags =
    ${env.build_flags}
    -D CONFIG_ASYNC_TCP_USE_WDT=1
    -D CONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
    -D CONFIG_ASYNC_TCP_PRIORITY=10
    -D CONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=15360
    -D DATAWEB=false
    -D SDCARD       ; comment if HW is not equipped with an SD card slot
    -D ROLE_RADIO

[env:btls_app]
build_src_filter = -<*> +<btls/> -<menu/>
build_flags = 
    ${env.build_flags}
    -D ROLE_BTLS
extra_scripts =
    ${env.extra_scripts}
    post:scripts/app_deploy.py
;Here the standard built-in Upload cannot be used to write the application,
;because PlatformIO cannot choose the correct partition to upload!
;You need to use the utility PROJECT TASKS/bt_app/Custom/Upload custom binary
lib_deps = 
    ${env.lib_deps}
    https://github.com/pschatzmann/ESP32-A2DP.git#v1.8.11
    https://github.com/Arduino-IRremote/Arduino-IRremote/archive/refs/tags/v4.7.1.zip




